name: CI

on:
  push:
    branches: [ "release/**" ]
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - uses: actions/checkout@v5

      - name: Display workflow envs
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Determine version (preview) - To release branch publish
        if: startsWith(github.ref_name, 'release/')
        run: |
          # Obtém o prefixo da versão a partir do nome do branch de release
          VERSION_PREFIX="${GITHUB_REF_NAME##*/}"          
          VERSION_SUFFIX="preview-${GITHUB_RUN_NUMBER}"
          
          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
          
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Determine version (stable) - To main branch publish from release pull request
        if: |
          github.event_name == 'pull_request' &&
          github.base_ref == 'main' &&
          github.event.pull_request.merged == true &&
          startsWith(github.head_ref, 'release/')
        run: |
          # Obtém o prefixo da versão a partir do nome do branch de origem do pull request
          VERSION_PREFIX="${GITHUB_HEAD_REF##*/}"          
          VERSION_SUFFIX=""
          
          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
          
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Validate determined version prefix with csproj file # Validação de segurança
        run: |
          CSPROJ_VERSION_PREFIX=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Version.props)
          echo "CSPROJ_VERSION_PREFIX: $CSPROJ_VERSION_PREFIX"
          
          if [ "$CSPROJ_VERSION_PREFIX" != "$VERSION_PREFIX" ]; then
            echo "Version prefix in csproj file ($CSPROJ_VERSION_PREFIX) does not match the determined version suffix ($VERSION_PREFIX)"
            exit 1
          fi

      - name: Pack
        run: dotnet pack src/Extensions.csproj --configuration Release --no-build -p:VersionPrefix="$VERSION_PREFIX" -p:VersionSuffix="$VERSION_SUFFIX"

      - name: Upload nupkg artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/bin/Release/*.nupkg

      - name: Publish release preview to MyGet
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestrianet/api/v3/index.json --api-key "${{ secrets.MYGET_API_KEY }}"

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
