name: CI

on:
  push:
    branches: [ 'release/**' ]
#    tags: [ '*' ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build
        
      - name: Determine version suffix
        id: version_suffix
        run: |
          branch="${GITHUB_REF##*/}"
          echo "Current branch: $branch"
          
          suffix=""
          if [[ $branch == release* ]]; then
            suffix="preview-${GITHUB_RUN_NUMBER}"
          fi
          
          echo "Determined version suffix: $suffix"
          echo "suffix=preview" >> $GITHUB_OUTPUT

      - name: Pack
        run: dotnet pack src/Extensions.csproj --configuration Release --no-build --version-suffix ${{ steps.version_suffix.outputs.suffix }}

      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/bin/Release/*.nupkg

      - name: Publish to MyGet
        if: github.ref == 'refs/heads/master'
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestria/api/v3/index.json --api-key ${{ secrets.MYGET_API_KEY }}
#
#      - name: Publish to NuGet
#        if: startsWith(github.ref, 'refs/tags/')
#        run: |
#          dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

