name: CI

on:
  push:
    branches: [ 'release/**' ]
#    tags: [ '*' ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        
      - name: Display workflow envs
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Determine version - To release publish
        id: version
        if: startsWith(github.ref_name, 'release/')
        run: |
          VERSION_PREFIX="${GITHUB_REF_NAME##*/}"          
          VERSION_SUFFIX="preview-${GITHUB_RUN_NUMBER}"
          
          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
          
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack src/Extensions.csproj --configuration Release --no-build -p:VersionPrefix="$VERSION_PREFIX" -p:VersionSuffix="$VERSION_SUFFIX"

      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/bin/Release/*.nupkg

      - name: Publish release preview to MyGet
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestrianet/api/v3/index.json --api-key "${{ secrets.MYGET_API_KEY }}"
                                                                
#
#      - name: Publish to NuGet
#        if: startsWith(github.ref, 'refs/tags/')
#        run: |
#          dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

