name: publish-versions

on:
  push:
    branches: [ "release/**" ]
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: Display github actions variables
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"

      - name: Checkout code - Preview version
        if: startsWith(github.ref_name, 'release/')
        uses: actions/checkout@v5

      - name: Checkout code - Stable version building from release branch merged to main
        if: |
          github.event_name == 'pull_request' &&
          github.base_ref == 'main' &&
          startsWith(github.head_ref, 'release/') &&
          github.event.pull_request.merged == true
        uses: actions/checkout@v5
        with:
          # branch name  (head_ref) já foi excluído devido a configurações de merge do repositório, então faz checkout direto no commit id
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Show branch and commit
        run: |
          git rev-parse --abbrev-ref HEAD
          git rev-parse HEAD

      - name: "Determine version: preview - Publish release branch"
        id: version-preview
        if: startsWith(github.ref_name, 'release/')
        run: |
          # Obtém o prefixo da versão a partir do nome do branch de release
          VERSION_PREFIX="${GITHUB_REF_NAME##*/}"          
          VERSION_SUFFIX="preview-${GITHUB_RUN_NUMBER}"
          
          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
          
          echo "version_determined=true" >> $GITHUB_OUTPUT
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: "Determine version: stable - Publish main branch, after release pull request is merged"
        id: version-stable
        if: |
          github.event_name == 'pull_request' &&
          github.base_ref == 'main' &&
          startsWith(github.head_ref, 'release/') &&
          github.event.pull_request.merged == true
        run: |
          # Obtém o prefixo da versão a partir do nome do branch de origem do pull request
          VERSION_PREFIX="${GITHUB_HEAD_REF##*/}"          
          VERSION_SUFFIX=""
          
          echo "VERSION_PREFIX: $VERSION_PREFIX"
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
          
          echo "version_determined=true" >> $GITHUB_OUTPUT
          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Abort if version was indeterminate
        if: steps.version-preview.outputs.version_determined == '' && steps.version-stable.outputs.version_determined == ''
        uses: actions/github-script@v8
        with:
          script: core.setFailed("Version could not be determined to branch workflow.");

      - name: Validate determined version prefix with csproj file # Validação de segurança
        run: |
          CSPROJ_VERSION_PREFIX=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Version.props)
          echo "CSPROJ_VERSION_PREFIX: $CSPROJ_VERSION_PREFIX"
          
          if [ "$CSPROJ_VERSION_PREFIX" != "$VERSION_PREFIX" ]; then
            echo "::error::Version prefix in csproj file ($CSPROJ_VERSION_PREFIX) does not match witch the determined version prefix from branch name ($VERSION_PREFIX)."
            exit 1
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack src/Extensions.csproj --configuration Release --no-build -p:VersionPrefix="$VERSION_PREFIX" -p:VersionSuffix="$VERSION_SUFFIX"

      - name: Upload nupkg artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: src/bin/Release/*.nupkg

      - name: Publish version to MyGet (preview)
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestrianet/api/v3/index.json --api-key "${{ secrets.MYGET_API_KEY }}"

      - name: Create pull request
        if: startsWith(github.ref_name, 'release/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_url=$(gh pr list --head "${GITHUB_REF_NAME}" --base "main" --state open --json url --jq .[].url)
          if [[ -n "${pr_url}" ]]; then
            echo "Pull Request already exists for branch '${GITHUB_REF_NAME}' to 'main': ${pr_url}"
          else
            gh pr create \
              -B main \
              -H "$GITHUB_REF_NAME" \
              --title "Merge \"$GITHUB_REF_NAME\" into main" \
              --body "Created by Github action"
          fi

      - name: Publish version to NuGet (stable)
        if: |
          github.event_name == 'pull_request' &&
          github.base_ref == 'main' &&
          startsWith(github.head_ref, 'release/') &&
          github.event.pull_request.merged == true
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      - name: Create release
        if: |
          github.event_name == 'pull_request' &&
          github.base_ref == 'main' &&
          startsWith(github.head_ref, 'release/') &&
          github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION_PREFIX" \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${VERSION_PREFIX}" \
              --generate-notes

  # Job to validate that publish completed successfully and allow merge to main (branch gate requirement on GitHub setting)
  validate-pr:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: OK
        run: echo "The publish job has completed successfully."
