name: validate-pr

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ "main" ]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display github actions variables
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
        
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Show branch and commit
        run: |
          git rev-parse --abbrev-ref HEAD
          git rev-parse HEAD

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0"

      - name: Display .NET Version
        run: dotnet --version

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build
